apiVersion: v1
kind: PersistentVolume
metadata:
  name: clarus-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/docker/pv-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clarus-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: clarus-pod
  labels:
    app: clarus-web 
spec:
  volumes:
    - name: clarus-pv-storage
      persistentVolumeClaim:
        claimName: clarus-pv-claim
  containers:
  - image: mysql:5.7
    name: mysql-db
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secrets
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secrets
          key: MYSQL_PASSWORD
    ports:
    - containerPort: 3306
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: clarus-pv-storage
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UmVhZGVyMQ==  # Base64 encoded value for "RootPassword1"
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=  # Base64 encoded value for "Clarusway_1"
