apiVersion: v1
kind: Pod
metadata:
  name: clarus-pod
  labels:
    app: clarus-web 
spec:
  volumes:
    - name: clarus-pv-storage
      persistentVolumeClaim:
        claimName: clarus-pv-claim
  containers:
  - image: mysql:5.7
    name: msql-db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: R1234r
    - name: MYSQL_DATABASE
      value: phonebook
    - name: MYSQL_USER
      value: clarus
    - name: MYSQL_PASSWORD
      value: Clarusway_1
    ports:
    - containerPort: 3306
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: clarus-pv-storage