apiVersion: v1
kind: PersistentVolume
metadata:
  name: proje-pv-vol
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/pv-data"